[default]
SECRET_KEY = 'martalindamaravilhosa'
EXTENSIONS = [
    "app.controllers.home:init_app",
    "app.controllers.employees:init_app",
    "app.controllers.companies:init_app",
    "app.controllers.checkout:init_app",
    "app.ext.database:init_app",
    "app.ext.wtforms:init_app",
    "app.ext.commands:init_app"
]

[development]
# docker run -d -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres --mount source=postgres,target=/var/lib/postgresql/data --name postgres postgres
# SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@localhost/development'
EXTENSIONS = [
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///'