[default]
SECRET_KEY = 'martalindamaravilhosa'
EXTENSIONS = [
    "app.ext.views.home:init_app",
    "app.ext.views.employees:init_app",
    "app.ext.views.companies:init_app",
    "app.ext.views.checkout:init_app",
    "app.ext.database:init_app",
    "app.ext.wtforms:init_app",
    "app.ext.commands:init_app"
]

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
EXTENSIONS = [
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///'

[production]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'