"""empty message

Revision ID: 8eb849b7124c
Revises: ca018e16f0f7
Create Date: 2022-10-30 17:48:48.583656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb849b7124c'
down_revision = 'ca018e16f0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('to_print', sa.Boolean(), nullable=True))
    op.drop_column('employees', 'for_print')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('for_print', sa.BOOLEAN(), nullable=True))
    op.drop_column('employees', 'to_print')
    # ### end Alembic commands ###
